/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "MainSettings": {
        "en": "Main settings",
        "de": "Haupteinstellungen",
        "ru": "Основные настройки",
        "pt": "Configurações principais",
        "nl": "Hoofdinstellingen",
        "fr": "Paramètres principaux",
        "it": "Impostazioni principali",
        "es": "Ajustes principales",
        "pl": "Główne ustawienie",
        "uk": "Основні налаштування",
        "zh-cn": "主要环境"
    },
    "AdditionalSettings": {
        "en": "Additional settings",
        "de": "Zusätzliche Einstellungen",
        "ru": "Дополнительные настройки",
        "pt": "Configurações adicionais",
        "nl": "Additie setting",
        "fr": "Paramètres supplémentaires",
        "it": "Impostazioni aggiuntive",
        "es": "Ajustes adicionales",
        "pl": "Dodatkowe ustawienie",
        "uk": "Додаткові налаштування",
        "zh-cn": "其他环境"
    },
    "HostIP": {
        "en": "Host/IP address",
        "de": "Host/IP-Adresse",
        "ru": "Host/IP адрес",
        "pt": "Endereço Host/IP",
        "nl": "Host/IP adres",
        "fr": "Adresse hôte/IP",
        "it": "Indirizzo host/IP",
        "es": "Host/IP address",
        "pl": "Adres host/IP",
        "uk": "Реєстрація",
        "zh-cn": "东道国/项目地址"
    },
    "HostIPDesc": {
        "en": "Hostname or IP address of nanoleaf Light Panels controller",
        "de": "Hostname oder IP-Adresse des nanoleaf Light Panels Controllers",
        "ru": "Hostname или IP-адрес контроллера нанолейфа Light Panels",
        "pt": "Nome de host ou endereço IP do controlador de painéis de luz nanoleaf",
        "nl": "Heetnaam of IP adres van nanoleaf Light Panels controller",
        "fr": "Nom d'hôte ou adresse IP du contrôleur des panneaux de lumière nanoleaf",
        "it": "Nome host o indirizzo IP del controller nanoleaf Light Panels",
        "es": "Nombre de host o dirección IP del controlador de paneles de luz nanoleaf",
        "pl": "Nazwy hostname lub adres IP na nanoleaf Light Panels kontroler",
        "uk": "Гість або IP-адреса контролера нанопластових панелей",
        "zh-cn": "纳米什小组控制员的人质或IP地址"
    },
    "searchDevice": {
        "en": "Search device",
        "de": "Gerät suchen",
        "ru": "Поиск устройства",
        "pt": "Dispositivo de pesquisa",
        "nl": "Zoek",
        "fr": "Appareil de recherche",
        "it": "Dispositivo di ricerca",
        "es": "Dispositivo de búsqueda",
        "pl": "Wyszukiwarka",
        "uk": "Пошук пристроїв",
        "zh-cn": "搜索装置"
    },
    "searchingDevices": {
        "en": "Searching device, please wait...",
        "de": "Geräte werden gesucht, bitte warten...",
        "ru": "Поиск устройства, пожалуйста, подождите.",
        "pt": "Procurando dispositivo, por favor, espere.",
        "nl": "Zoekapparaat, wacht.",
        "fr": "L'appareil de recherche, s'il vous plaît attendez.",
        "it": "Dispositivo di ricerca, si prega di aspettare.",
        "es": "Buscar dispositivo, por favor espere.",
        "pl": "Poszukiwania urządzeń, czekaj.",
        "uk": "Шукайте пристрій, будь ласка, почекайте.",
        "zh-cn": "搜寻装置,请等。."
    },
    "DevicesFound": {
        "en": "Device(s) found and can be selected in the list above.",
        "de": "Gerät(e) wurde(n) gefunden und konnen in der Liste oben ausgewählt werden.",
        "ru": "Устройство(ы) найдено и может быть выбрано в списке выше.",
        "pt": "Dispositivo(s) encontrado e pode ser selecionado na lista acima.",
        "nl": "Gevonden en geselecteerd in de lijst boven.",
        "fr": "Les périphériques trouvés et peuvent être sélectionnés dans la liste ci-dessus.",
        "it": "Dispositivo(i) trovato e può essere selezionato nell'elenco sopra.",
        "es": "Dispositivo(s) encontrado y se puede seleccionar en la lista anterior.",
        "pl": "Device(s) znalazło się i można je wybrać na liście powyżej.",
        "uk": "Пристрої(и) знайдено і можна вибрати в списку вище.",
        "zh-cn": "目 录."
    },
    "DevicesNotFound": {
        "en": "No devices found! Try to enter manually the IP address or hostname.",
        "de": "Es wurden keine Geräte gefunden! Versuche die manuelle Eingabe der IP-Adresse oder Hostname.",
        "ru": "Не найдено устройств! Попробуйте ввести вручную IP-адрес или имя хоста.",
        "pt": "Nenhum dispositivo encontrado! Tente inserir manualmente o endereço IP ou nome de host.",
        "nl": "Geen apparaten gevonden! Probeer handmatig het IP-adres of gastnaam binnen te komen.",
        "fr": "Pas d'appareils trouvés ! Essayez d'entrer manuellement l'adresse IP ou le nom d'hôte.",
        "it": "Nessun dispositivo trovato! Cerca di inserire manualmente l'indirizzo IP o il nome host.",
        "es": "¡No hay dispositivos encontrados! Intente introducir manualmente la dirección IP o el nombre de host.",
        "pl": "Nie znaleziono żadnych urządzeń. Próbuje wejść w ręcznie adres IP lub hostname.",
        "uk": "Не знайдено пристроїв Спробуйте ввести вручну IP-адресу або ім'я користувача.",
        "zh-cn": "没有发现的装置 准备手册地址或名称。."
    },
    "Port": {
        "en": "Port",
        "de": "Port",
        "ru": "Порт",
        "pt": "Port",
        "nl": "Port",
        "fr": "Port",
        "it": "Port",
        "es": "Port",
        "pl": "Port",
        "uk": "Портфоліо",
        "zh-cn": "港口"
    },
    "PortDesc": {
        "en": "HTTP port of nanoleaf light panels controller",
        "de": "HTTP-Port des nanoleaf Light Panels Controllers",
        "ru": "HTTP порт контроллера световых панелей",
        "pt": "Porta HTTP do controlador de painéis de luz nanoleaf",
        "nl": "HTP port nanoleaf lichtpanelen controller",
        "fr": "Port HTTP du contrôleur de panneaux de lumière nanoléaf",
        "it": "Porta HTTP del controller di pannelli leggeri nanoleaf",
        "es": "HTTP port of nanoleaf light panel controlador",
        "pl": "Strona internetowa portalu internetowego",
        "uk": "HTTP-порт нанолистових світлових панелей контролер",
        "zh-cn": "HTTP港口 纳迪小组控制员"
    },
    "AuthToken": {
        "en": "Authentification token",
        "de": "Authentifizierungs-Token",
        "ru": "Authentification токен",
        "pt": "Token de autenticação",
        "nl": "Authentificatie",
        "fr": "Jeton d ' authentification",
        "it": "Token di autenticazione",
        "es": "Token de autentificación",
        "pl": "Token",
        "uk": "Аверсифікація токен",
        "zh-cn": "事实"
    },
    "AuthTokenDesc": {
        "en": "Authentification token for nanoleaf Light Panels OpenAPI.<br>Enter if you have already a token.<br>Otherweise this can be obtained by clicking on the \"Obtain authorization token\" button. The device has to be in paring mode (press and hold power button for 5-7 seconds).",
        "de": "Authentifizierungs-Token der nanoleaf Light Panels OpenAPI.<br>Wenn vorhanden, kann dieser hier eingegeben werden. Ansonsten kann dieser über den Button \"Authentifizierungs-Token anfordern\" angefordert werden. Das Gerät muss sich dazu im Pairing-Modus befinden (Power-Taste 5-7 Sekunden gedrückt halten).",
        "de": "Authentifikationstoken für Nanoleaf Lichttafeln OpenAPI.<br> Geben Sie ein, wenn Sie bereits ein Token haben.< br>Gerade kann dies durch Anklicken des \"\\Berechtigungstokens\"\\-Buttons erreicht werden. Das Gerät muss im Paring-Modus sein (Drucken und halten Power-Taste für 5-7 Sekunden).",
        "ru": "Authentification токен для нанолейфа Световые панели OpenAPI.<br> Введите, если у вас уже есть токен.< br>Otherweise это можно получить, нажав на кнопку \"\\Obtain авторизации token\"\\. Устройство должно быть в режиме паринга (пресс и удерживать кнопку питания в течение 5-7 секунд).",
        "pt": "Token de autenticação para nanoleaf Painéis de luz OpenAPI.<br> Insira se você já tiver um token.< br>Otherweise isso pode ser obtido clicando no botão \"\\Obtain autorizada token\"\\. O dispositivo tem de estar no modo de paring (pressione e segure o botão de energia por 5-7 segundos).",
        "nl": "Authentificatie voor Nanoleaf Lichte Panels open. Kom binnen als je al een teken hebt. Dit kan worden verkregen door het kliken van de \"Obtain autorisatie token\" knop. Het apparaat moet in paringsmodus zitten en krachtknop houden voor 5-7 seconden.",
        "fr": "Jeton d'authentification pour nanoleaf Panneau lumineux OpenAPI. Entrez si vous avez déjà un jeton. Ceci peut être obtenu en cliquant sur le bouton \"\\Obtain authorization token\"\\. L'appareil doit être en mode paring (pression et maintien du bouton de puissance pendant 5-7 secondes).",
        "it": "Token di autenticazione per nanoleaf Pannelli di luce OpenAPI. Inserisci se hai già un token. br>Altrimenti si può ottenere cliccando sul pulsante \"\\Obtain autorizzate token\"\\. Il dispositivo deve essere in modalità paring (premi e tieni premuto il pulsante di accensione per 5-7 secondi).",
        "es": "Token de autentificación para nanoleaf Paneles de luz OpenAPI. Entra si ya tienes una ficha. br títuloOtrosiste esto se puede obtener haciendo clic en el botón \"\\Obtener autorización token\"\\. El dispositivo tiene que estar en modo de paring (presione y mantenga el botón de potencia durante 5-7 segundos).",
        "pl": "Authentification token Light Panels OpenAPI (ang.). Wejście, jeśli masz już ten znak. br>Otherweise to można uzyskać poprzez kliknięcie na przycisk autoryzacji. Urządzenie musi być w trybie parowania (przycisk i przycisk mocy 5-7 sekund).",
        "uk": "Перевірити токен для нанолефа Світлові панелі OpenAPI.<br> Увійдіть, якщо у вас вже є токен. br>Використовувати це можна за допомогою натискання на кнопку «Записатись» Пристрій має бути в режимі пароля (прес і утримувати кнопка живлення на 5-7 секунд).",
        "zh-cn": "Authentation for娜页 光学小组:<br> 如果你已经过去了。 可通过点击“软禁”的许可而取得的“其他优势”。 装置必须有诱惑(压制和持有5-7秒)。."
    },
    "GetAuthToken": {
        "en": "Obtain authorization token",
        "de": "Authentifizierungs-Token anfordern",
        "ru": "Получить токен авторизации",
        "pt": "Obtenção de autorização",
        "nl": "Vertaling:",
        "fr": "Obtention de l ' autorisation",
        "it": "Ottenere il token di autorizzazione",
        "es": "Obtener la autorización token",
        "pl": "Przypisy",
        "uk": "Отримання авторизації токен",
        "zh-cn": "B. 拘留许可"
    },
    "PollingInterval": {
        "en": "Polling interval",
        "de": "Abfrage-Intervall",
        "ru": "Поллинг интервал",
        "pt": "Intervalo de Polling",
        "nl": "Vertaling:",
        "fr": "Intervalle de vote",
        "it": "Intervallo d'inquinamento",
        "es": "Intervalo de votación",
        "pl": "Interwał",
        "uk": "Проміжок поля",
        "zh-cn": "干预"
    },
    "PollingIntervalDesc": {
        "en": "Interval in ms for status update polling (only until LightPanels firmware version 3.1.0 and Canvas 1.1.0)",
        "de": "Intervall in ms für regelmäßige Statusabfrage (nur bis LightPanels Firmware Version 3.1.0 und Canvas 1.1.0)",
        "ru": "Интервал в мс для опроса обновления статуса (только до версии прошивки LightPanels 3.1.0 и Canvas 1.1.0)",
        "pt": "Intervalo em ms para votação de atualização de status (apenas até LightPanels versão de firmware 3.1.0 e Canvas 1.1.0)",
        "nl": "Quality over Quantity Releases Vertaling:",
        "fr": "Intervalle en ms pour la mise à jour du statut (seulement jusqu'à la version 3.1.0 du firmware LightPanels et Canvas 1.1.0)",
        "it": "Intervallo in ms per l'aggiornamento dello stato di polling (solo fino a LightPanels versione firmware 3.1.0 e Canvas 1.1.0)",
        "es": "Intervalo en ms para encuestas de actualización de estado (sólo hasta la versión de firmware LightPanels 3.1.0 y Canvas 1.1.0)",
        "pl": "Interval in ms for status update polling (do czasu aż do wersji 3.1.0 i Canvas 1.1.0)",
        "uk": "Інтервал в мс для оновлення стану (тільки до версії прошивки LightPanels 3.1.0 і Canvas 1.1.0)",
        "zh-cn": "最新投票情况差异(直到图书公司掌握的3.1和1.0%)"
    },
    "ReconnectInterval": {
        "en": "Reconnect interval",
        "de": "Wiederverbindungs-Intervall",
        "ru": "Reconnect интервал",
        "pt": "Reconectar intervalo",
        "nl": "Verbindingsmiddelen",
        "fr": "Intervalle de raccordement",
        "it": "Intervallo di connessione",
        "es": "Intervalos de conexión",
        "pl": "Przepustowość",
        "uk": "Інтервал відключення",
        "zh-cn": "B. 连带"
    },
    "ReconnectIntervalDesc": {
        "en": "Interval in seconds for reconnection attempts",
        "de": "Intervall in Sekunden für erneute Versuche die Verbindung herzustellen",
        "ru": "Интервал в секундах для попыток повторного подключения",
        "pt": "Intervalo em segundos para tentativas de reconexão",
        "nl": "Interval in seconden voor verbindingspogingen",
        "fr": "Intervalle en quelques secondes pour les tentatives de reconnection",
        "it": "Intervallo in pochi secondi per tentativi di riconnessione",
        "es": "Intervalo en segundos para intentos de reconexión",
        "pl": "Zainteresowanie próbami ponownego połączenia",
        "uk": "Інтервал за секундами для спроб відключення",
        "zh-cn": "二. 重新连接企图的二者之间的间隔"
    },
    "OnSaveRestartHint": {
        "en": "Adapter restarts immediately with new config on save",
        "de": "Beim Speichern wird der Adapter sofort neugestartet.",
        "ru": "Адаптер перезапуск немедленно с новым config на спасении",
        "pt": "Adapter reinicia imediatamente com nova configuração em salvar",
        "nl": "Adapter herstelt onmiddellijk met een nieuw configuur op redding",
        "fr": "Adaptateur redémarre immédiatement avec une nouvelle configuration pour sauver",
        "it": "L'adattatore si riavvia immediatamente con nuova configurazione su salvare",
        "es": "Adaptador se reinicia inmediatamente con nuevo config en guardar",
        "pl": "Adapter restartuje natychmiast z nowym konfigurem",
        "uk": "Перезавантаження адаптера відразу з новим настроєм на збереження",
        "zh-cn": "紧紧紧要的艺术品是新一块暗淡的。"
    },
    "AdapterNotAlive": {
        "en": "Adapter must be running!",
        "de": "Adater muss gestartet sein!",
        "ru": "Адаптер должен работать!",
        "pt": "O adaptador deve estar a correr!",
        "nl": "Adapter moet vluchten!",
        "fr": "L'adaptateur doit fonctionner !",
        "it": "L'adattatore deve essere in esecuzione!",
        "es": "¡El adaptador debe estar funcionando!",
        "pl": "Żebym się biegać!",
        "uk": "Адаптер повинен працювати!",
        "zh-cn": "必须道歉!"
    },
    "AdapterStateTitle": {
        "en": "Adapter state",
        "de": "Adapter Zustand",
        "ru": "Адаптер государство",
        "pt": "Estado do adaptador",
        "nl": "Adapter staat",
        "fr": "État adaptateur",
        "it": "Stato dell'adattatore",
        "es": "Adapter state",
        "pl": "Państwa Adapterów",
        "uk": "Стан адаптера",
        "zh-cn": "州"
    },
    "ObtainAuthTokenWait": {
        "en": "Obtaining authorization token, please wait...",
        "de": "Authentifizierungs-Token wird angefordert, bitte warten... ",
        "ru": "Получение токена авторизации, пожалуйста, подождите.",
        "pt": "Obtendo autorização, por favor, espere.",
        "nl": "Betreffende toestemmingskaart, wacht.",
        "fr": "S'il vous plaît attendre.",
        "it": "Ottenere l'autorizzazione token, si prega di attendere.",
        "es": "Obteniendo la autorización token, por favor espere.",
        "pl": "Objęcie symbolu autoryzacji, czy czekasz.",
        "uk": "Зберігаючи авторизації, будь ласка, почекайте.",
        "zh-cn": "获得授权,请等候。."
    },
    "ErrorGetAuthTokenTitle": {
        "en": "Error while obtaining",
        "de": "Fehler beim Anfordern",
        "ru": "Ошибка при получении",
        "pt": "Erro ao obter",
        "nl": "Error terwijl het verkrijgen van",
        "fr": "Erreur lors de l ' obtention",
        "it": "Errore durante l'ottenimento",
        "es": "Error al obtener",
        "pl": "Errorowi udało się otrzymać",
        "uk": "Помилка при отриманні",
        "zh-cn": "获取许可证"
    },
    "ErrorJSON": {
        "en": "Invalid response (JOSN expected). For more details see log!",
        "de": "Ungültige Antwort (JSON erwartet). Weitere Details siehe Log!",
        "ru": "Недействительный ответ (JOSN ожидаемый). Для более подробной информации см. журнал!",
        "pt": "Resposta inválida (JOSN esperado). Para mais detalhes, consulte o log!",
        "nl": "Ongeldig antwoord. Voor meer details zie je logboek!",
        "fr": "Réponse non valide (JOSN attendu). Pour plus de détails, consultez le journal !",
        "it": "Risposta non valida (si aspettava JOSN). Per maggiori dettagli vedi log!",
        "es": "Respuesta inválida (esperada por JOSN). Para más detalles vea el registro!",
        "pl": "Invalid Request (ang.). Na więcej szczegółów można zobaczyć logowanie!",
        "uk": "Очікувана відповідь (Очікується JOSN). Детальніше див. журнал!",
        "zh-cn": "评价反应(JOSN预期)。 详情见逻辑!"
    },
    "ErrorUnauthorized": {
        "en": "Access denied/unauthorized. Is the device in pairing mode?<br>To set the device into pairing mode press and hold the power button at the device for 5-7 seconds until the LEDs at the device flash alternately.",
        "de": "Zugriff verweigert/nicht autorisiert. Ist das Gerät im Pairing-Modus?<br>Um das Gerät in den Pairing-Modus zu versetzen, muss die Power-Taste am Gerät 5-7 Sekunden gedrückt gehalten werden, bis die LEDs am Gerät abwechselnd leuchten.",
        "ru": "Доступ запрещен/несанкционированно. Является ли устройство в паровом режиме?<br> Чтобы установить устройство в режим парения нажмите и удерживайте кнопку питания на устройстве в течение 5-7 секунд до светодиодов на устройстве поочередно.",
        "pt": "Acesso negado/não autorizado. O dispositivo é em modo de emparelhamento?<br> Para definir o dispositivo em modo de emparelhamento pressione e segure o botão de energia no dispositivo por 5-7 segundos até os LEDs no flash do dispositivo alternadamente.",
        "nl": "Toegang geweigerd/onauthoriseerd. Is het apparaat in mode? Om het apparaat in koppelende druk te zetten en de krachtknop te houden op het apparaat voor 5-7 seconden tot de LED's bij het apparaat alternatief.",
        "fr": "Accès refusé/non autorisé. L'appareil est-il en mode de jumelage? Pour régler l'appareil en mode de jumelage appuyez sur et maintenez le bouton de puissance sur l'appareil pendant 5-7 secondes jusqu'à ce que les LED sur l'appareil clignotent alternativement.",
        "it": "Accesso negato/non autorizzato. Il dispositivo è in modalità di accoppiamento? Per impostare il dispositivo in modalità di accoppiamento premere e tenere premuto il pulsante di accensione sul dispositivo per 5-7 secondi fino a quando i LED al dispositivo lampeggiano alternativamente.",
        "es": "Acceso denegado/no autorizado. ¿El dispositivo está en modo de emparejamiento? Para configurar el dispositivo en modo de emparejamiento presione y mantenga el botón de potencia en el dispositivo durante 5-7 segundos hasta que los LEDs en el dispositivo flash alternativamente.",
        "pl": "Uchwalony lub nieautoryzowany. Czy to urządzenie w trybie parowania? Aby utworzyć urządzenie do parowania modowej prasy i przetrzymywania przycisku mocy na 5-7 sekund, aż LED w urządzenie automatycznie zmienia się.",
        "uk": "Відхилено/несанкціоновано. Чи працює пристрій в режимі пари?<br> Щоб встановити пристрій в режим паріння натисніть і утримуйте кнопку живлення на пристрої протягом 5-7 секунд до тих пір, поки світлодіоди на пристрої спалахують по черзі.",
        "zh-cn": "拒绝/不予批准。 装配方式中的装置吗? 安装配制媒体的装置,在5-7秒的装置上持有5至7秒的权力,直到该装置被复燃。."
    },
    "ErrorConnection": {
        "en": "Error while connecting. For more details see log!",
        "de": "Fehler beim Verbindungsaufbau. Weitere Details siehe Log!",
        "ru": "Ошибка при подключении. Для более подробной информации см. журнал!",
        "pt": "Erro ao ligar. Para mais detalhes, consulte o log!",
        "nl": "Error terwijl hij verbindt. Voor meer details zie je logboek!",
        "fr": "Erreur pendant la connexion. Pour plus de détails, consultez le journal !",
        "it": "Errore durante la connessione. Per maggiori dettagli vedi log!",
        "es": "Error al conectarse. Para más detalles vea el registro!",
        "pl": "Error podczas łączenia. Na więcej szczegółów można zobaczyć logowanie!",
        "uk": "Помилка при підключенні. Детальніше див. журнал!",
        "zh-cn": "联系时间。 详情见逻辑!"
    },
    "NoAuthTokenFound": {
        "en": "No authentification token found. See log for more details!",
        "de": "Kein Authentifizierungs-Token gefunden. Weitere Details siehe Log!",
        "ru": "Не найден токен аутентификации. Для более подробной информации см. журнал!",
        "pt": "Nenhum token de autenticação encontrado. Para mais detalhes, consulte o log!",
        "nl": "Geen authentificatie teken gevonden. Voor meer details zie je logboek!",
        "fr": "Aucun signe d'authentification n'a été trouvé. Pour plus de détails, consultez le journal !",
        "it": "Nessun token di autenticazione trovato. Per maggiori dettagli vedi log!",
        "es": "No hay registro de autentificación encontrado. Para más detalles vea el registro!",
        "pl": "Nie znaleziono autentyfikacji. Na więcej szczegółów można zobaczyć logowanie!",
        "uk": "Не знайдено authentification token. Детальніше див. журнал!",
        "zh-cn": "没有发现任何理由。 详情见逻辑!"
    },
    "SuccessGetAuthToken": {
        "en": "Authentification token usccessfully obtained!",
        "de": "Authentifizierungs-Token anfordern erfolgreich!",
        "ru": "Authentification token успешно получен!",
        "pt": "Autenticação token usccessfully obtidos!",
        "nl": "Authentificatie token wekelijks verkregen!",
        "fr": "Authentification token usccessfully obtained!",
        "it": "Authentification token usciti con successo!",
        "es": "Authentification token usccesssfully obtained!",
        "pl": "Authentification token!",
        "uk": "Аутентифікація токену намобно одержувати!",
        "zh-cn": "对我们所希望的团结!"
    },
    "disableSSE": {
        "en": "Disable Server Sent Events (SSE)",
        "de": "Server Sent Events (SSE) deaktivieren",
        "ru": "Отключить сервер Sent Events (SSE)",
        "pt": "Desativar eventos enviados para servidor (SSE)",
        "nl": "Disable Server Sent Events (SSE)",
        "fr": "Désactiver les événements du serveur (SSE)",
        "it": "Disattiva eventi client server (SSE)",
        "es": "Eventos de Servidor Desactivado (SSE)",
        "pl": "Oficjalna strona Server Sent Events (ang.)",
        "uk": "Вимкнути Сервер Sent Події (SSE)",
        "zh-cn": "可支配的服务活动(SSE)"
    },
    "adapterAddress": {
        "en": "Adapter address",
        "de": "Adapter-Adresse",
        "ru": "Адаптер адрес",
        "pt": "Endereço do adaptador",
        "nl": "Adapteradres",
        "fr": "Adresse adaptatrice",
        "it": "Indirizzo dell'adattatore",
        "es": "Dirección de adaptación",
        "pl": "Adres Adaptera",
        "uk": "Адреса адаптера",
        "zh-cn": "道歉"
    },
    "Listen on all IPs": {
        "en": "Listen on all IPs",
        "de": "Auf alle IPs hören",
        "ru": "Слушайте на всех IP",
        "pt": "Ouça todos os IPs",
        "nl": "Luister naar alle IP's",
        "fr": "Écoutez tous les IP",
        "it": "Ascolta tutti gli IP",
        "es": "Escucha todos los IPs",
        "pl": "Lista wszystkich IP",
        "uk": "Послухайте всі IP-адреси",
        "zh-cn": "所有IP清单"
    },
    "keepAlivePolling": {
        "en": "Use polling instead of SSDP notify messages for keep alive detection",
        "de": "Polling anstatt SSDP Notify Messages für Keep-Alive verwenden",
        "ru": "Используйте загрязнение вместо SSDP оповещать сообщения, чтобы сохранить живое обнаружение",
        "pt": "Use sondagem em vez de mensagens de notificação SSDP para manter a detecção viva",
        "nl": "Gebruik peilingen in plaats van SSDP berichten voor levende detectie",
        "fr": "Utilisez le sondage au lieu de SSDP notifier les messages pour garder la détection vivante",
        "it": "Utilizzare il polling invece di SSDP notificare i messaggi per mantenere il rilevamento vivo",
        "es": "Usar encuestas en lugar de SSDP notificar mensajes para mantener la detección viva",
        "pl": "Zastosowanie sondy zamiast SD powiadomiło komunikaty o zachowaniu żywej detekcji",
        "uk": "Використовуйте опитування замість SSDP, щоб зберегти жива виявлення",
        "zh-cn": "使用污染而不是全国测绘中心通知信息,以保持活性探测"
    },
    "keepAlivePollingInterval": {
        "en": "Keep alive polling intervall",
        "de": "Keep-Alive Polling-Intervall",
        "ru": "Держите живой загрязняющий интервал",
        "pt": "Mantenha o intervalo de votação vivo",
        "nl": "Blijf leven in de peiling",
        "fr": "Garder les intervalles de sondage vivants",
        "it": "Tenere l'intervallo di polling vivo",
        "es": "Mantener el intervalo de votación viva",
        "pl": "Keep live polling intervall (ang.)",
        "uk": "Зберігати проміжок часу живого опитування",
        "zh-cn": "A. 进行活性投票"
    },
    "keepAlivePollingIntervalDec": {
        "en": "Interval in seconds for connection detection",
        "de": "Intervall in Sekunden für Verbindungserkennung",
        "ru": "Интервал в секундах для обнаружения соединения",
        "pt": "Intervalo em segundos para detecção de conexão",
        "nl": "Vertaling:",
        "fr": "Intervalle en quelques secondes pour la détection de connexion",
        "it": "Intervallo in secondi per il rilevamento della connessione",
        "es": "Interval en segundos para detección de conexiones",
        "pl": "Interwal w sekundach do detekcji połączeń",
        "uk": "Інтервал за секундами для виявлення з'єднання",
        "zh-cn": "二. 探查的二者之间的间隔"
    },
};
